### PR TITLE
some changes in home.css  and style.css which improved the website.

### PR DESCRIPTION
**Pull request by maheshwar04**
I noticed that the homepage was not fully covering the screen, and the cards were outside the container. Therefore, I made some improvements

### CODE REVIEW

**Comment by himanshu251001** [comment]
> I noticed that the homepage was not fully covering the screen, and the cards were outside the container. Therefore, I made some improvements

Please complete the issue mentioned by updating the UI design of login and sing up page

**Comment by maheshwar04** [comment]
ok I will update it

**Comment by maheshwar04** [comment]
"I updated the UI of the signup and login pages by making  background attached and increasing the size of the form, input fields, and fonts. I believe the changes have resulted in a more visually appealing design compared to the previous version.Now you will love this

**Comment by himanshu251001** [comment]
> "I updated the UI of the signup and login pages by making background attached and increasing the size of the form, input fields, and fonts. I believe the changes have resulted in a more visually appealing design compared to the previous version.Now you will love this

Do same for login page.Try changing its background image . Send me a request again i will merge your request .

**Comment by maheshwar04** [comment]
I changed the background image of login page, which enhanced the page, and made some improvements to the login form.

**Comment by himanshu251001** [comment]
I am satisfied with your work.Well Done.

**Comment by maheshwar04** [comment]
not showing in hackodex dashboard,why.

**Comment by himanshu251001** [comment]
> not showing in hackodex dashboard,why.

i dont't know about that

**Comment by maheshwar04** [comment]
Thanks now showing.

**Pull request merged**
